function sway = importswayfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  sway = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  sway = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  AN12MO92ONclosed1 = importswayfile("/Users/deborahapthorp/Dropbox (Personal)/UNE/Supervision/Alycia Messing/Data/Data October 2023/Study 2/Raw/T1/Sway T1/AN12MO92ON_closed_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Nov-2023 15:39:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EventCounter", "Sync", "Aux", "Fz", "Mx", "My", "COPx", "COPy"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sway = readtable(filename, opts);

end