function participants = importParticipants(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARTICIPANTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PARTICIPANTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Participants = importfile("/Users/deborahapthorp/Dropbox (Personal)/UNE/Supervision/Alycia Messing/Data/Data October 2023/Study 2/MATLAB code/Participants.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Nov-2023 07:59:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Participant", "Group"];
opts.VariableTypes = ["char", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Participant", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Participant", "Group"], "EmptyFieldRule", "auto");

% Import the data
participants = readtable(filename, opts);

end